### ISSUE TITLE
Quant Assignment 1 final version to be graded

### ISSUE THREAD

**Issue by ryan6351** [SES-5215-F2020/rjohnson-quant#1]
All files are ready (I hope!) - thanks! They are given the name "NewAssignment1.(Rmd/html)."

**Comment by saratepfer** [comment]
Great job on this assignment! Your code is clear, and it is clear from your work that you have: selected and identified the required variables, identified the population and number of observations, and identified the unit of analysis.

**Comment by ryan6351** [comment]
Thank you!
