### ISSUE TITLE
Quant assignment 3 ready for grading!

### ISSUE THREAD

**Issue by ryan6351** [SES-5215-F2020/rjohnson-quant#3]
Good evening y'all! 

I've finished my submission for assignment 3, and it can be found at this link: https://ses-5215-f2020.github.io/rjohnson-quant/Assignment3Quant.html

P.S. I'm especially proud of the heatmap I put together for the chi-squared test (I believe the differences between observed and expected values, which I plotted, are called _residuals_ - is that correct?)! 

Thanks,

Ryan

**Comment by saratepfer** [comment]
Thank you, Ryan! Nice job on this! Please see a few comments below:

- Annual household income v. monthly rent scatter plot: Nice job using paste() and prettyNum() to create y-axis labels that include commas and dollar signs for clarity. I would do this for the x axis labels as well (for clarity and consistency)
- For each of your Pearson correlation interpretations, I would be sure to reference both the strength and _the significance_ of your result. In some cases you only refer to the strength, when significance is also important.
- Really nice job with the heat map!
- It would be great to see some interpretations of your Tukey HSD tests.
