### ISSUE TITLE
Assignment 5 ready for grading

### ISSUE THREAD

**Issue by ryan6351** [SES-5215-F2020/rjohnson-quant#5]
Good afternoon, 

Assignment #5 (I can't believe it's the last one!) is ready for grading - it can be found here: https://ses-5215-f2020.github.io/rjohnson-quant/Assignment5Quant.html

Thanks for teaching such a great course - I always felt naturally averse to any kind of coding, and so I've been pleasantly surprised to actually enjoy this course (as well as VIS). 

Best,

Ryan

**Comment by saratepfer** [comment]
Nice job, Ryan! It would be great to see some interpretation of the second graph you chose to include in your conclusions/visualization section.
